### ISSUE TITLE
Empty devices list

### ISSUE THREAD

**Issue by JohannCR** [zigbee2mqtt/hassio-zigbee2mqtt#594] opened 2024-04-09 21:57 UTC
### Description of the issue

All devices disappeared from the addon's devices list. They are still present in the integration page, and still work.
Since 1.36.1-1 I've been uninstalling and reinstalling switching between the stable and edge versions to try to fix some ghost bindings that broke a couple of devices. Since then, I don't know why, the devices list is now empty. As if the database.db was corrupted in some way... When I open it, it looks good and contains all devices though.

Tried clearing cache, rebooting addon, reloading integration, rebooting HA, no change.

Is there a way to fix this ? Like removing the database, reboot and then putting it back or something like that ?

### Addon version

edge. Can't find commit hash, but it's the same on stable anyway

### Platform

Core
2024.4.1
Supervisor
2024.04.0
Operating System
12.1
Interface utilisateur
20240404.1

### Logs of the issue (if applicable)

Nothing in the logs

**Comment by JohannCR** [comment] 2024-04-15 21:47
For those wondering, I have not found any solution other than deleting everything and restarting from scratch repairing every device... That was a pain 🤣

**Comment by nrehn** [comment] 2024-05-09 09:24
Hi. I have the same issue now. 
Device list is empty but everything works. 
It does not work to join devices either. When pressing the button in GUI nothing happens.

**Comment by martintm86** [comment] 2024-06-06 09:26
Hello, for me it happens today after Update 2024.6.0. Everything works but i cant configure anything in the Zigbee2MQTT menu. All empty and without function... 

Reboot and clearing cache does not fix that...

**Comment by Astromechdroide** [comment] 2024-06-08 06:11
> Hello, for me it happens today after Update 2024.6.0. Everything works but i cant configure anything in the Zigbee2MQTT menu. All empty and without function...
> 
> Reboot and clearing cache does not fix that...

I have the same problem. Is there a solution?

**Comment by JohannCR** [comment] 2024-06-08 06:24
> I have the same problem. Is there a solution?

Only one I tested successfully was to uninstall and delete all devices, reinstall and repair everything... Painful. 
Plus I don't know why (may not be linked to this issue) but I have more devices disconnecting from the network since. Unfortunately I also changed my coordinator so I don't know what caused those disconnections. Again, may not be linked to z2m.
Try repairing all if your network isn't too big and don't hesitate to report back 😉

**Comment by martintm86** [comment] 2024-06-11 11:19
After update to 2024.6.1 everything is fixed for me....

**Comment by Operrr** [comment] 2024-06-14 00:46
My version is XA 2024.6.1, version Z2M 
1.38.0-1 the list of devices is empty, but everything seems to work. Connecting new devices does not work, there are no logs, no information. Help me please!

![1](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/24464676/8c535b7d-c3a6-475d-a259-7a62fa55ef2e)

**Comment by booroondook-eng** [comment] 2024-06-17 08:38
The same problem, but I see empty devices list (and also empty Dashboard) in **ingress** mode only.
When I switch to normal mode (open http://<my-address>:8099 in the new browser window) I see completed list of my devices and working Dashboard).
In other words: The problem with empty devices list appears in the ingress mode only.

**Comment by Operrr** [comment] 2024-06-17 22:38
I can't open the page directly

**Comment by Operrr** [comment] 2024-06-28 13:09
Is it really possible that no one else has such a problem and there will be no help?

**Comment by martintm86** [comment] 2024-07-02 07:20
For me the Problem comes with my Apache Reverse Proxy. In the Browser Console i have seen that it can't open a special WebSocket URL. After Adding it to reverse Proxy config anything is ok....
Before if i connect directly to HA by IP the Plugin was OK

ProxyPass /api/hassio_ingress ws://192.168.2.4:80/api/hassio_ingress
ProxyPassReverse /api/hassio_ingress ws://192.168.2.4:80/api/hassio_ingress

**Comment by pdm0** [comment] 2024-07-21 11:06
> Is it really possible that no one else has such a problem and there will be no help?

You are not alone in this. Unfortunately I am in the same situation and despite considerable efforts have not found any fix.

**Comment by Operrr** [comment] 2024-07-25 10:49
I solved the problem. If you clear the "devices" section directly in "/homeassistant/zigbee2mqtt/configuration.yaml" then all device names and descriptions will disappear, but the device list will work correctly. After everything worked, I manually entered device descriptions using the old backup. Now everything is fine.

**Comment by booroondook-eng** [comment] 2024-07-25 11:39
I found another way to resolve this problem.
My configuration.yaml contains the following string:
`devices: devices.yaml`
...and all devices' configuration stores in the devices.yaml file.
I noticed that this file has very large size: about 5 MB.
The reason for this size was that this file contains icons of all my devices in base64 format. I removed all the lines with icons, the file was reduced to about 4 kilobytes, and the problem with the empty device list completely disappeared!

**Comment by Netpoet** [comment] 2024-08-09 05:48
@booroondook-eng 
Thanks a lot! I had the same issue, and your hint helped! I cleared all the image information lines from the config, restarted the coordinator and Home Assistant, and voilà, everything's back!
<3

**Comment by ahamro** [comment] 2024-08-28 06:20
> I found another way to resolve this problem. My configuration.yaml contains the following string: `devices: devices.yaml` ...and all devices' configuration stores in the devices.yaml file. I noticed that this file has very large size: about 5 MB. The reason for this size was that this file contains icons of all my devices in base64 format. For example:
> 
> ```
> '0xa4c1380d5fXXXXXX':
>   friendly_name: Zigbee Lamp 2
>   icon: >-
>     data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAYAAAA8.... etc
> ```
> 
> I removed all the lines with icons, the file was reduced to about 4 kilobytes, and the problem with the empty device list completely disappeared!

You're the best! In my case the devices are in zigbee2mqtt/configuration.yaml and after weeding out the icon lines the devices list and the dashboard were populated again. Including the icons. Great! Thanks for sharing your solution!

**Comment by xelemorf** [comment] 2024-09-20 23:27
Great finding, I was getting nuts by bumping into this bug all the time!

I have identified that the "Localise device images" feature is doing this, flooding the configuration .yaml with base64 images to a point where Z2M just cannot handle. In my case it also was not able to finish the localization of images as it was already too much with my 147 devices, failed around 100.

![image](https://github.com/user-attachments/assets/6eaceabb-0867-44a0-9375-5798a016fb8e)


@Koenkk, can you please remove this "Localise device images" feature completely from Z2M for now?
I think embedding images and any substantial amount of data into the main config file will always end up badly, maybe having them externally stored as jpg files in an z2m_img folder and referencing them by device id would be more fruitful. Thank you.

**Comment by Koenkk** [comment] 2024-09-21 19:17
@xelemorf interesting finding, I guess z2m didn't startup anymore in your case?

**Comment by xelemorf** [comment] 2024-09-21 22:45
> @xelemorf interesting finding, I guess z2m didn't startup anymore in your case?

Z2M could still start without showing any errmsg but none of my devices were present on the default UI, while they were still working as expected in all HA automations, scripts and on Lovelace.
Had to enable the front-end tcp-listen port 8099 to be able to see my devices in Z2M there.

After the fix I've mentioned everything works as expected. Using currently available latest Z2M stable with latest HAOS.

**Comment by Koenkk** [comment] 2024-09-23 18:11
Interesting, do you still have the debug log of this? Could also be a frontend issue

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by xelemorf** [comment] 2024-09-23 18:51
I'll try to find some time over the weekend to collect debug logs.

**Comment by silfax** [comment] 2024-09-26 20:29
> > @xelemorf interesting finding, I guess z2m didn't startup anymore in your case?
> 
> @Koenkk Z2M could still start without showing any errmsg but none of my devices were present on the default UI, while they were still working as expected in all HA automations, scripts and on Lovelace. Had to enable the front-end tcp-listen port 8099 to be able to see my devices in Z2M there _(sidenote for the front-end 8099: it does not have any protection and could login without auth)._
> 
> After the fix I've mentioned everything works as expected. Using currently available latest Z2M stable with latest HAOS.
> 
> Btw once had this issue, I also could not get the file from "request z2m backup" or "download state", and "network map" also never finished - works after the fix.

I can confirm the same behavior with probably the same cause ('Localize device images'). Z2M appears to be working normally, device list only available by accessing it via port 8099. Didn't have the time to try cleaning devices.yaml (currently >5 MB). Will do it during weekend. Will also try to collect some logs before as well.

**Comment by xelemorf** [comment] 2024-10-27 09:47
> Interesting, do you still have the debug log of this? Could also be a frontend issue
> 
> See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

Apologies for the delay, life just stepped in and did not have any spare time since, however I could make some time today and managed to peform a **successful repro**.

Z2M configuration.yaml debug setting (Z2M service restarted after changing):
  log_debug_to_mqtt_frontend: true
  log_level: debug

Size of configuration.yaml:
Orig: 42.6KB
Localised: 6.01MB

[Localtime: 10:25] The localization on the UI stalled marking items "done", however, all devices in config were processed.
[Localtime: 10:30] Devices still showing up in Z2M at this point. 
[Localtime: 10:33] Stopped Z2M service. 
[Localtime: 10:34] Started Z2M service. 
[Localtime: 10:34] Devices are not showing up, all devices dissapeared. Repro successful. 
[Localtime: 10:36] Stopped Z2M service: 
[Localtime: 10:40] Config restored, Z2M service started, devices are shown

![Z2M_Localise device images_01](https://github.com/user-attachments/assets/eab3128f-db29-4184-ba85-903538c5b892)
![Z2M_Localise device images_02](https://github.com/user-attachments/assets/6f9803a4-c5e2-4822-b515-ef6b43209981)
![Z2M_Localise device images_03](https://github.com/user-attachments/assets/1eb5a81b-a5b1-4c15-aa77-4852b154a7c5)
![Z2M_Localise device images_04](https://github.com/user-attachments/assets/b9283e6e-fea4-405e-b6c9-b5586ed0ba05)

[Z2M_Localise device images_LOGS.txt](https://github.com/user-attachments/files/17533407/Z2M_Localise.device.images_LOGS.txt) Please rename to Z2M_Localise device images_LOGS.**7z**

**Comment by xelemorf** [comment] 2024-11-05 21:22
> > Interesting, do you still have the debug log of this? Could also be a frontend issue
> > See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.
> 
> @Koenkk Apologies for the delay, life just stepped in and did not have any spare time since, however I could make some time today and managed to peform a **successful repro**.
> 
> Z2M configuration.yaml debug setting (Z2M service restarted after changing): log_debug_to_mqtt_frontend: true log_level: debug
> 
> Size of configuration.yaml: Orig: 42.6KB Localised: 6.01MB
> 
> [Localtime: 10:25] The localization on the UI stalled marking items "done", however, all devices in config were processed. [Localtime: 10:30] Devices still showing up in Z2M at this point. [Localtime: 10:33] Stopped Z2M service. [Localtime: 10:34] Started Z2M service. [Localtime: 10:34] Devices are not showing up, all devices dissapeared. Repro successful. [Localtime: 10:36] Stopped Z2M service: [Localtime: 10:40] Config restored, Z2M service started, devices are shown
> 
> Showing the process for Localise device images, which appears to be stalled after "kitchen-mainlight": ![Z2M_Localise device images_01](https://private-user-images.githubusercontent.com/979681/380484687-eab3128f-db29-4184-ba85-903538c5b892.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDE3MzIsIm5iZiI6MTczMDg0MTQzMiwicGF0aCI6Ii85Nzk2ODEvMzgwNDg0Njg3LWVhYjMxMjhmLWRiMjktNDE4NC1iYTg1LTkwMzUzOGM1Yjg5Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMTE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmE4MTFiNjRkOGViZGFiZDAzZTFkZDYwOWY2YzVlNDIxYzU3ZGE5NzhiYzVmN2VjNGE1NTAyMThhNzU4MDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ubfh70diw6GsI4N7_SsUii9LX602ROlasYhbaV0E60Y)
> 
> Showing the empty device list after localise device images completed and a Z2M restart: ![Z2M_Localise device images_02](https://private-user-images.githubusercontent.com/979681/380484689-6f9803a4-c5e2-4822-b515-ef6b43209981.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDE3MzIsIm5iZiI6MTczMDg0MTQzMiwicGF0aCI6Ii85Nzk2ODEvMzgwNDg0Njg5LTZmOTgwM2E0LWM1ZTItNDgyMi1iNTE1LWVmNmI0MzIwOTk4MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMTE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjc1ZTA0YjViMjI5NGRhZTFmODZkN2VlYWQ2OTllZTc1ZGM3MGI3MGU5MDMzZmZjZGUwZmVhYjhmZjQxNGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KCAMSsAFshk_JzqVkUmVvH1kCQFjNHZK-k_FH9xoK7I)
> 
> Showing a device list after the config restore: ![Z2M_Localise device images_03](https://private-user-images.githubusercontent.com/979681/380484690-1eb5a81b-a5b1-4c15-aa77-4852b154a7c5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDE3MzIsIm5iZiI6MTczMDg0MTQzMiwicGF0aCI6Ii85Nzk2ODEvMzgwNDg0NjkwLTFlYjVhODFiLWE1YjEtNGMxNS1hYTc3LTQ4NTJiMTU0YTdjNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMTE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzM3YTEwNDYyMjAxOTI2YWU3ZDgwMGNhYjUzMmVjODE2OWQzMmE4MmU1OWRmYWM2OTJlMWVmM2NhMmI0ZWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UjHluFmt-uMWpTKCaWct3wv1NLKf3sqNjmcCq9xTdQM)
> 
> Showing Z2M version and device count: ![Z2M_Localise device images_04](https://private-user-images.githubusercontent.com/979681/380484691-b9283e6e-fea4-405e-b6c9-b5586ed0ba05.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDE3MzIsIm5iZiI6MTczMDg0MTQzMiwicGF0aCI6Ii85Nzk2ODEvMzgwNDg0NjkxLWI5MjgzZTZlLWZlYTQtNDA1ZS1iNmM5LWI1NTg2ZWQwYmEwNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMTE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTc1NzQzMTgzNzJkOGYyYjQwZWI4OWU2ODhiMGQzYmJlMDNkNWFmNDA2NzQyODAyNDcwMGU1NmIzY2U3ZGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7-kZArt7lxJwcwQgDjhv98lzSgwWFsgG-Jf3ckPRb40)
> 
> Could not upload 7z or logs directly, in-line would have been flooding so renamed it to **txt** extension. Please rename to Z2M_Localise.device.images_LOGS_u3.**7z** [Z2M_Localise.device.images_LOGS_u3.txt](https://github.com/user-attachments/files/17533502/Z2M_Localise.device.images_LOGS_u3.txt)
> 
> PS: Would be great if the following sensitive data would not be exposed in the debug log by the way, each property have multiple types of exposure: extendedPanID, panID, channelList. I've marked all references as REDACTED.

@Koenkk: Ping

**Comment by Semicolon7645** [comment] 2024-11-25 17:45
> For me the Problem comes with my Apache Reverse Proxy. In the Browser Console i have seen that it can't open a special WebSocket URL. After Adding it to reverse Proxy config anything is ok.... Before if i connect directly to HA by IP the Plugin was OK
> 
> ProxyPass /api/hassio_ingress ws://192.168.2.4:80/api/hassio_ingress ProxyPassReverse /api/hassio_ingress ws://192.168.2.4:80/api/hassio_ingress

This is what fixed it for me. I had to re-install Ubuntu on my server and when I re-setup Nginx Proxy Manager, I forgot the enable Websockets for the proxy host I added for the Z2M web ui. Thank you.

**Comment by xelemorf** [comment] 2024-12-26 09:01
Let's keep this open

**Comment by Koenkk** [comment] 2024-12-28 13:06
The image localise issue will be fixed in https://github.com/Koenkk/zigbee2mqtt/pull/25299

**Comment by xelemorf** [comment] 2024-12-28 16:19
> The image localise issue will be fixed in [Koenkk/zigbee2mqtt#25299](https://github.com/Koenkk/zigbee2mqtt/pull/25299)

Greatly appreciated @Koenkk, thank you!

**Comment by xelemorf** [comment] 2024-12-28 16:24
@JohannCR, please consider closing this issue based on the above.

**Closed** 2024-12-28 16:26 UTC

**Comment by sanderlv** [comment] 2025-08-15 08:14
I still have this issue with all latest updates applied. List stays empty. If I go to an inprivate browser tab it works. I have clear all cache multiple times that does not work. Also the issue persists in 3 browsers: Edge, Opera, Firefox.
