### ISSUE TITLE
Zigbee2mqtt won't start after updating to 1.17.1-1

### ISSUE THREAD

**Issue by fss** [zigbee2mqtt/hassio-zigbee2mqtt#26] opened 2021-02-12 10:47 UTC
After updating to 1.17.1-1 my add-on won't start, printing this error message:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[11:45:15] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[11:45:16] INFO: MQTT available, fetching server detail ...
[11:45:16] INFO: Previous config file found, checking backup
[11:45:16] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[11:45:16] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:45:17] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
Zigbee2MQTT:error 2021-02-12 11:45:21: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-12 11:45:21: Failed to start zigbee
Zigbee2MQTT:error 2021-02-12 11:45:21: Exiting...
Zigbee2MQTT:error 2021-02-12 11:45:21: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-12T10_45_21_998Z-debug.log
```

Core: core-2021.2.3
Home Assistant OS 5.11

**Comment by Murada99** [comment] 2021-02-12 10:55
After this update, zigbee2mqtt don't start.
Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[11:53:26] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[11:53:29] INFO: MQTT available, fetching server detail ...
[11:53:30] INFO: Previous config file found, checking backup
[11:53:30] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[11:53:31] INFO: File devices.js found, copying to ./node_modules/zigbee-herdsman-converters/
cp: can't create './node_modules/zigbee-herdsman-converters/devices.js': No such file or directory
[cont-init.d] zigbee2mqtt.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by ciotlosm** [comment] 2021-02-12 11:06
@fss your error is `'Error: Error: No such file or directory, cannot open /dev/ttyACM0'` which means your serial port is unavailable. Are you running in a VM or native HassOS setup?

@Murada99  your error is related to devices.js cutomisation which is not really the recommended (and supported) method for adding custom devices. See the docs here for the new method: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#adding-support-for-new-devices

**Comment by fss** [comment] 2021-02-12 11:08
@ciotlosm I'm running HassOS, but it might be my Supervisor version being super-old (and it refuses to update)

**Comment by ciotlosm** [comment] 2021-02-12 11:09
@fss you can go to the Supervisor / Hardware as stated in the Notes of docs and find out which named serial port to use:

`To find out which serial ports you have exposed go to Supervisor → System → Host system → ⋮ → Hardware`

**Comment by fss** [comment] 2021-02-12 11:11
@ciotlosm yeah I know ;) the device is copied from there and it all worked perfectly until today :)

**Comment by fss** [comment] 2021-02-12 11:18
@ciotlosm I managed to update Supervisor to latest version, now the error message is slightly changed:

```
Zigbee2MQTT:error 2021-02-12 12:17:39: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-12 12:17:39: Failed to start zigbee
Zigbee2MQTT:error 2021-02-12 12:17:39: Exiting...
Zigbee2MQTT:error 2021-02-12 12:17:39: Error: Error while opening serialport 'Error: Error: Operation not permitted, cannot open /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001949CABE-if00'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
```

**Comment by Murada99** [comment] 2021-02-12 11:29
@ciotlosm Thanks, I removed the file and now it starts. It was working until this update but now I need to change the way to add new devices.

**Comment by fss** [comment] 2021-02-12 11:32
@ciotlosm is this supposed to work?

```
chmod 777 /dev/ttyACM0
chmod: /dev/ttyACM0: Read-only file system
```

**Comment by ciotlosm** [comment] 2021-02-12 11:53
@fss I don't think that's supposed to work. Mine works without any mods, so might be worth trying to fix your old supervisor. 

@Murada99 I'm sure someone might know how to make it work with the custom devices in the new version, but it's worth learning the new way as it's much more stable between version upgrades.

**Comment by fss** [comment] 2021-02-12 12:00
as said, I was able to update Supervisor to the latest version but file system permissions seem completely borked now. on a friend's setup listing /dev/tty* shows chmod of 777 meaning the port can be written to, whereas on mine it's in some weird `audio` group and writing is not possible.

**Comment by ciotlosm** [comment] 2021-02-12 12:08
@fss where are you running the commands? In the terminal addon or on the host?

**Comment by fss** [comment] 2021-02-12 12:09
@ciotlosm in the terminal addon

**Comment by ciotlosm** [comment] 2021-02-12 12:13
@fss i have also the audio group, but I have w enabled, but I'm running HassOS 5.4. I'll upgrade to see if it reproduces. I posted in #27 my details as it seems multiple people have problems with /dev and readonly.

**Comment by fss** [comment] 2021-02-12 12:59
@ciotlosm FYI, I'm running core-2021.2.3, supervisor-2021.02.6, Home Assistant OS 5.11

thanks!

**Comment by NL18958** [comment] 2021-02-12 13:23
Hi, I am having an issue too. MQTT won't start. I think there is something wrong with one of the zigbee devices from the old setup. I will have a check tonight.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[14:07:40] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[14:07:49] INFO: MQTT available, fetching server detail ...
[14:07:50] INFO: MQTT server settings not configured, trying to auto-discovering ...
[14:07:52] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[14:07:52] INFO: MQTT credentials not configured, trying to auto-discovering ...
[14:07:53] INFO: Configuring'addons' mqtt user
[14:07:53] INFO: Previous config file found, checking backup
[14:07:53] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[14:07:54] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:07:57] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
assert.js:105
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Converter field exposes is undefined
    at validateDefinition (/app/node_modules/zigbee-herdsman-converters/index.js:52:16)
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:59:5)
    at new ExternalConverters (/app/lib/extension/externalConverters.js:13:38)
    at new Controller (/app/lib/controller.js:77:34)
    at Object.<anonymous> (/app/index.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'notStrictEqual'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-12T13_08_23_975Z-debug.log
[14:08:25] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js`

**Comment by ciotlosm** [comment] 2021-02-12 13:25
@NL18958 your MQTT is fine, it just says it auto-discovered the connection. The problem is probably with a customization you are running. Are you using any custom "devices.js" in your setup?

**Comment by NL18958** [comment] 2021-02-12 13:34
I did change devices.js previously for a zigbee device that is not standard available. Never got it to work, when upgrading to 1.17.0. I will remove the entry in devices.js tonight and post back here.

**Comment by xtrem16081987** [comment] 2021-02-12 14:52
![image](https://user-images.githubusercontent.com/71350781/107782441-c0d69900-6d51-11eb-8327-75b369a7226f.png)
![image](https://user-images.githubusercontent.com/71350781/107782674-02ffda80-6d52-11eb-8dc6-19918b700a7c.png)
![image](https://user-images.githubusercontent.com/71350781/107782717-114df680-6d52-11eb-80b8-832ff33b6dab.png)
![image](https://user-images.githubusercontent.com/71350781/107782921-507c4780-6d52-11eb-9b74-51231a5517c1.png)
![image](https://user-images.githubusercontent.com/71350781/107782943-57a35580-6d52-11eb-9fbc-b500cec17228.png)
![image](https://user-images.githubusercontent.com/71350781/107783018-7275ca00-6d52-11eb-815b-722b321fd0a2.png)
The usb stick is detected but as a GENERIC !  wich i think that there is a driver issue or kernel issue on the HA side . 

Also output from my zigbee2mqtt add-on 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[14:51:57] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[14:51:58] INFO: MQTT available, fetching server detail ...
[14:51:59] INFO: Previous config file found, checking backup
[14:51:59] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[14:51:59] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:52:00] INFO: Zigbee Herdsman debug logging enabled
[14:52:00] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
Zigbee2MQTT:info  2021-02-12 14:52:07: Logging to console and directory: '/share/zigbee2mqtt/log/2021-02-12.14-52-04' filename: log.txt
Zigbee2MQTT:info  2021-02-12 14:52:07: Starting Zigbee2MQTT version 1.17.1 (commit #1.17.1)
Zigbee2MQTT:info  2021-02-12 14:52:07: Starting zigbee-herdsman (0.13.59)
2021-02-12T14:52:08.004Z zigbee-herdsman:adapter:zStack:znp:error Failed to determine if path is valid: 'Error: ENOTDIR: not a directory, lstat '/dev/tty/ttyS0''
2021-02-12T14:52:08.047Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-02-12T14:52:08.052Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/tty/ttyS0"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-02-12T14:52:08.056Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/tty/ttyS0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
Zigbee2MQTT:error 2021-02-12 14:52:08: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-12 14:52:08: Failed to start zigbee
Zigbee2MQTT:error 2021-02-12 14:52:08: Exiting...
Zigbee2MQTT:error 2021-02-12 14:52:08: Error: Error while opening serialport 'Error: Error: Not a directory, cannot open /dev/tty/ttyS0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-12T14_52_08_173Z-debug.log

**Comment by NL18958** [comment] 2021-02-13 13:40
> 
> 
> I did change devices.js previously for a zigbee device that is not standard available. Never got it to work, when upgrading to 1.17.0. I will remove the entry in devices.js tonight and post back here.

Finally got it to work, I had to change file 'freepad_ext.js'. Once I copied back the example code, the add on works again. I hope this helps someone that has the same issue. The problem was that my code for a device that is not supported wasn't working.

**Comment by RIP21** [comment] 2021-02-13 15:51
Have exactly the same issue as topic starter.  More info here.
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/27#issuecomment-778636591

**Comment by ciotlosm** [comment] 2021-02-15 08:30
Closing this issue as it's covered under #27 for the readonly problem and under #25 for the devices.js problem.

**Closed by ciotlosm** 2021-02-15 08:30 UTC
