### ISSUE TITLE
Unable to control MS-108ZR (curtain module) over the add-on

### ISSUE THREAD

**Issue by DerNiccoo** [zigbee2mqtt/hassio-zigbee2mqtt#660] opened 2024-11-25 16:25 UTC
### Description of the issue

Hey, recently I did the update to the current HA Version: 2024.11.2. I've also updated every add-on. Since the update, all of my Zigbee + RF curtain switch module (MS-108ZR) from Moes can not be correctly controlled with the add-on anymore. When I control them over z2m directly, it works as expected. I do not get an error message, but I've attached the DEBUG log. As you hopefully can see in the small recording is me trying to control the curtain. In the start they are open but as you can see I can only press up. They move and stop. What does work is changing the % with the slider. Then they move correct. I can also stop them as you see and then use up to bring them up. But after that they are again in this strange state.

https://github.com/user-attachments/assets/34550bb9-eada-443b-9274-cb2e02aac078

### Addon version

v1.41

### Platform

Core: 2024.11.2 (docker)

### Logs of the issue (if applicable)

```
2024-11-25 16:15:25.582 DEBUG (MainThread) [homeassistant.components.mqtt.client] local.homeassistant: register write 28
2024-11-25 16:15:25.584 DEBUG (MainThread) [homeassistant.components.mqtt.client] local.homeassistant: unregister write 28
2024-11-25 16:15:29.848 DEBUG (MainThread) [homeassistant.components.mqtt.client] local.homeassistant: register write 28
2024-11-25 16:15:29.848 DEBUG (MainThread) [homeassistant.components.mqtt.client] Transmitting message on zigbee2mqtt/Büro Rolladen/set: 'OPEN', mid: 391, qos: 0
2024-11-25 16:15:29.850 DEBUG (MainThread) [homeassistant.components.mqtt.client] local.homeassistant: unregister write 28
2024-11-25 16:15:29.971 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on zigbee2mqtt/Büro Rolladen (qos=0): b'{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}'
2024-11-25 16:15:29.972 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'position_open': 100, 'position_closed': 0, 'tilt_min': 0, 'tilt_max': 100, 'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({{ value_json.position }}) renders=61>
2024-11-25 16:15:29.972 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['installed_version'] }}) renders=61>
2024-11-25 16:15:29.973 DEBUG (MainThread) [homeassistant.components.mqtt.update] Non-dictionary JSON payload detected after processing payload '71' on topic zigbee2mqtt/Büro Rolladen
2024-11-25 16:15:29.973 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'sensor.buro_rolladen_moving', 'name': 'Moving', 'this': <template TemplateStateFromEntityId(sensor.buro_rolladen_moving)>} with default value 'default' and Template<template=({{ value_json.moving }}) renders=61>
2024-11-25 16:15:29.973 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'number.buro_rolladen_calibration_time', 'name': 'Calibration time', 'this': <template TemplateStateFromEntityId(number.buro_rolladen_calibration_time)>} and Template<template=({{ value_json.calibration_time }}) renders=61>
2024-11-25 16:15:29.973 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({"in_progress": {{ iif(value_json['update']['state'] == 'updating', 'true', 'false') }} }) renders=61>
2024-11-25 16:15:29.974 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['latest_version'] }}) renders=61>
2024-11-25 16:15:29.974 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({% if "moving" in value_json and value_json.moving %} {{ value_json.moving }} {% else %} STOP {% endif %}) renders=61>
2024-11-25 16:15:29.974 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"UP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'switch.buro_rolladen_motor_reversal', 'name': 'Motor reversal', 'this': <template TemplateStateFromEntityId(switch.buro_rolladen_motor_reversal)>} and Template<template=({{ value_json.motor_reversal }}) renders=61>
2024-11-25 16:15:30.157 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on zigbee2mqtt/Büro Rolladen (qos=0): b'{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}'
2024-11-25 16:15:30.158 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'position_open': 100, 'position_closed': 0, 'tilt_min': 0, 'tilt_max': 100, 'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({{ value_json.position }}) renders=62>
2024-11-25 16:15:30.158 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['installed_version'] }}) renders=62>
2024-11-25 16:15:30.159 DEBUG (MainThread) [homeassistant.components.mqtt.update] Non-dictionary JSON payload detected after processing payload '71' on topic zigbee2mqtt/Büro Rolladen
2024-11-25 16:15:30.159 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'sensor.buro_rolladen_moving', 'name': 'Moving', 'this': <template TemplateStateFromEntityId(sensor.buro_rolladen_moving)>} with default value 'default' and Template<template=({{ value_json.moving }}) renders=62>
2024-11-25 16:15:30.159 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'number.buro_rolladen_calibration_time', 'name': 'Calibration time', 'this': <template TemplateStateFromEntityId(number.buro_rolladen_calibration_time)>} and Template<template=({{ value_json.calibration_time }}) renders=62>
2024-11-25 16:15:30.159 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({"in_progress": {{ iif(value_json['update']['state'] == 'updating', 'true', 'false') }} }) renders=62>
2024-11-25 16:15:30.160 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['latest_version'] }}) renders=62>
2024-11-25 16:15:30.160 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({% if "moving" in value_json and value_json.moving %} {{ value_json.moving }} {% else %} STOP {% endif %}) renders=62>
2024-11-25 16:15:30.160 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":78,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'switch.buro_rolladen_motor_reversal', 'name': 'Motor reversal', 'this': <template TemplateStateFromEntityId(switch.buro_rolladen_motor_reversal)>} and Template<template=({{ value_json.motor_reversal }}) renders=62>
2024-11-25 16:15:30.268 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on zigbee2mqtt/Büro Rolladen (qos=0): b'{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}'
2024-11-25 16:15:30.268 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'position_open': 100, 'position_closed': 0, 'tilt_min': 0, 'tilt_max': 100, 'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({{ value_json.position }}) renders=63>
2024-11-25 16:15:30.269 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['installed_version'] }}) renders=63>
2024-11-25 16:15:30.269 DEBUG (MainThread) [homeassistant.components.mqtt.update] Non-dictionary JSON payload detected after processing payload '71' on topic zigbee2mqtt/Büro Rolladen
2024-11-25 16:15:30.269 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'sensor.buro_rolladen_moving', 'name': 'Moving', 'this': <template TemplateStateFromEntityId(sensor.buro_rolladen_moving)>} with default value 'default' and Template<template=({{ value_json.moving }}) renders=63>
2024-11-25 16:15:30.269 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'number.buro_rolladen_calibration_time', 'name': 'Calibration time', 'this': <template TemplateStateFromEntityId(number.buro_rolladen_calibration_time)>} and Template<template=({{ value_json.calibration_time }}) renders=63>
2024-11-25 16:15:30.270 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({"in_progress": {{ iif(value_json['update']['state'] == 'updating', 'true', 'false') }} }) renders=63>
2024-11-25 16:15:30.270 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'update.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(update.buro_rolladen)>} and Template<template=({{ value_json['update']['latest_version'] }}) renders=63>
2024-11-25 16:15:30.270 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'cover.buro_rolladen', 'name': None, 'this': <template TemplateStateFromEntityId(cover.buro_rolladen)>} and Template<template=({% if "moving" in value_json and value_json.moving %} {{ value_json.moving }} {% else %} STOP {% endif %}) renders=63>
2024-11-25 16:15:30.271 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"calibration":"ON","calibration_time":27,"linkquality":75,"motor_reversal":"OFF","moving":"STOP","position":0,"state":"CLOSE","update":{"installed_version":71,"latest_version":71,"state":"idle"},"update_available":null}' with variables {'entity_id': 'switch.buro_rolladen_motor_reversal', 'name': 'Motor reversal', 'this': <template TemplateStateFromEntityId(switch.buro_rolladen_motor_reversal)>} and Template<template=({{ value_json.motor_reversal }}) renders=63>

```

**Comment by Koenkk** [comment] 2024-11-27 07:24
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/24597

**Closed by Koenkk** 2024-11-27 07:24 UTC
