### ISSUE TITLE
Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by wifiuk** [zigbee2mqtt/hassio-zigbee2mqtt#515] opened 2023-08-03 09:35 UTC
### Discovered MQTT entities with a name that is equal to the device name
```
This stops working in version 2024.2.0. Please address before upgrading.
Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

redacted
```

### Discovered entities with a name that starts with the device name

```
This stops working in version 2024.2.0. Please address this before upgrading.
Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

redacted
```

Is this linked to this ticket?
https://github.com/home-assistant/core/issues/97656

### Addon version

1.32.2-1

### Platform

Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

**Comment by bushbrother** [comment] 2023-08-03 15:55
https://github.com/Koenkk/zigbee2mqtt/issues/18445 - known about, will be in September release I understand from various threads.

**Comment by Koenkk** [comment] 2023-08-03 17:33
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Closed by Koenkk** 2023-08-03 17:33 UTC
