### ISSUE TITLE
Failed to start zigbee

### ISSUE THREAD

**Issue by remcopoulus** [zigbee2mqtt/hassio-zigbee2mqtt#33] opened 2021-02-15 21:02 UTC
**Description of problem:**
I am running this plugin on my Home Assistant. After I rebooted the system everything failed to start, due to an update from Supervisor. So I downgraden supervisor, restored a snapshot, but then zigbee2mqtt was gone.. I was using danielwelch/hassio-zigbee2mqtt which migrated to here I saw.
So I installed this version 1.17.1-4, updated the config to what I had before:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: my_user
  password: my_pass
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

When starting I get errors:
```
Zigbee2MQTT:error 2021-02-15 21:57:22: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-15 21:57:22: Failed to start zigbee
Zigbee2MQTT:error 2021-02-15 21:57:22: Exiting...
Zigbee2MQTT:error 2021-02-15 21:57:22: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.2.1
Supervisor: supervisor-2021.01.7
Operating System: Docker version 18.09.8
```
My Supervisor System Hardware shows:
```
serial:
  - /dev/ttyACM0
  - >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014DA4C0E-if00
  - /dev/ttyS0
  - /dev/ttyS1
  - /dev/ttyS2
  - /dev/ttyS3
input:
  - Sleep Button
  - Video Bus
  - Power Button
disk: []
gpio:
  - gpiochip0
usb:
  - /dev/bus/usb/001/001
  - '/dev/1-0:1.0'
  - /dev/bus/usb/001/003
  - '/dev/1-10:1.0'
  - '/dev/1-10:1.1'
  - /dev/bus/usb/001/002
  - '/dev/1-9:1.0'
  - /dev/bus/usb/002/001
  - '/dev/2-0:1.0'
audio: {}
```
So the device is available. 

**Your logs from Home Assistant Supervisor**
```
21-02-15 20:05:49 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.17.1-4

21-02-15 20:08:22 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_core_mosquitto application
21-02-15 20:08:22 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
21-02-15 20:08:31 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-02-15 20:08:32 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-02-15 20:09:06 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 5.1
21-02-15 20:09:07 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
21-02-15 20:10:00 INFO (SyncWorker_3) [supervisor.docker.interface] Removing image zigbee2mqtt/zigbee2mqtt-amd64 with latest and 1.17.1-4
21-02-15 20:10:01 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/7ad98f9c_zigbee2mqtt
21-02-15 20:10:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-15 20:10:01 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 7ad98f9c_zigbee2mqtt
21-02-15 20:10:01 INFO (MainThread) [supervisor.addons] Add-on '7ad98f9c_zigbee2mqtt' successfully removed
21-02-15 20:12:33 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_mosquitto application
21-02-15 20:12:34 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application



21-02-15 20:23:37 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-15 20:23:37 INFO (MainThread) [supervisor.resolution.check] System checks complete

21-02-15 20:28:57 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting homeassistant/qemux86-64-homeassistant
21-02-15 20:29:07 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-02-15 20:29:42 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-02-15 20:31:49 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting homeassistant/qemux86-64-homeassistant
21-02-15 20:31:57 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-02-15 20:32:32 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance

21-02-15 20:35:40 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 5.1
21-02-15 20:35:41 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
21-02-15 20:36:26 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-nginx_proxy with version 3.0.1
21-02-15 20:37:46 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-rpc_shutdown with version 2.2
21-02-15 20:37:54 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/aircast/amd64 with version 3.0.0

21-02-15 20:41:16 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/danielwelch/hassio-zigbee2mqtt
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/deconz/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/homematic/config.json: does not match regular expression for dictionary value @ data['schema']['hmip'][0]['device']. Got 'device(subsystem=tty)'
does not match regular expression for dictionary value @ data['schema']['rf'][0]['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/zwave/config.json: does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/zwave_js/config.json: does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/node-red/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/ssh/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/wireguard/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/net/tun'
21-02-15 20:41:16 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/zerotier/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/net/tun'
21-02-15 20:41:16 INFO (MainThread) [supervisor.store] Loading add-ons from store: 57 all - 0 new - 2 remove
21-02-15 20:41:46 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/deconz/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/homematic/config.json: does not match regular expression for dictionary value @ data['schema']['hmip'][0]['device']. Got 'device(subsystem=tty)'
does not match regular expression for dictionary value @ data['schema']['rf'][0]['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/zwave/config.json: does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/zwave_js/config.json: does not match regular expression for dictionary value @ data['schema']['device']. Got 'device(subsystem=tty)'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/node-red/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/ssh/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/mem'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/wireguard/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/net/tun'
21-02-15 20:41:47 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a0d7b954/zerotier/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/net/tun'
21-02-15 20:41:47 INFO (MainThread) [supervisor.store] Loading add-ons from store: 59 all - 2 new - 0 remove

21-02-15 20:44:43 CRITICAL (MainThread) [supervisor.jobs] The following job conditions are ignored and will make the system unstable when they occur: {<JobCondition.HEALTHY: 'healthy'>}
21-02-15 20:44:43 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/45df7312_zigbee2mqtt
21-02-15 20:44:43 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.17.1-4.
21-02-15 20:44:54 INFO (MainThread) [supervisor.addons] Add-on '45df7312_zigbee2mqtt' successfully installed
21-02-15 20:47:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-15 20:47:46 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 45df7312_zigbee2mqtt

21-02-15 20:48:21 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.17.1-4
```

**Comment by dielessen** [comment] 2021-02-23 11:04
I have the same issue on 1.17.1-4:

Zigbee2MQTT:error 2021-02-23 11:57:29: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-23 11:57:29: Failed to start zigbee
Zigbee2MQTT:error 2021-02-23 11:57:29: Exiting...
Zigbee2MQTT:error 2021-02-23 11:57:29: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12

Previous versions are working without any problems . I have a zzh! stick with the latest firmware.

**Comment by rolandb5** [comment] 2021-02-27 00:57
I got the same issue... have seen it working before, but now I also encounter this issue.

**Comment by remcopoulus** [comment] 2021-02-27 13:01
My solution was switching to separate docker containers and not using supervisor for the package.
See instructions here: https://www.youtube.com/watch?v=reg1Hf0eKTU

**Comment by brianacox** [comment] 2021-03-01 16:49
Not sure (sorry I'm new to this) if it is the same problem, but I'm hitting problems (which I can't overcome) when things appeared to work ok before; I've done this on two Macs now....

[16:44:36] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
Zigbee2MQTT:error 2021-03-01 16:44:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-01 16:44:59: Failed to start zigbee
Zigbee2MQTT:error 2021-03-01 16:44:59: Exiting...
Zigbee2MQTT:error 2021-03-01 16:44:59: Error: SREQ '--> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T16_45_00_076Z-debug.log
[16:45:00] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js

**Comment by rolandb5** [comment] 2021-03-01 18:04
I resolved the issue by reflashing.

**Comment by brianacox** [comment] 2021-03-01 18:06
> I resolved the issue by reflashing.

mmmm.  I brought mine already set up (flashed) and I'm fairly new to this so I will keep trying to contact Slaesh (who I got the card from) but he's seemed to have disappeared for the last few weeks... something must have come up.

**Comment by ciotlosm** [comment] 2021-03-05 08:32
I'm using zzh! and it's been working now with latest updates (1.18.1-1).

**Comment by brianacox** [comment] 2021-03-05 09:11
> I'm using zzh! and it's been working now with latest updates (1.18.1-1).

Were you not before?  (were you using MTQQ & Zigbee?)

**Comment by dielessen** [comment] 2021-03-05 09:50
I can confirm with 1.18.1-1 it works again.

**Comment by ciotlosm** [comment] 2021-03-05 09:52
@brianacox zzh! as in the adapter. I've been using it for a while, but before i was using cc2531. What I was trying to say is that with the supervisor and hassos and latest z2m add-on everything works for me. I will close the issue for now. Any problems please raise a new issue.

**Closed by ciotlosm** 2021-03-05 09:52 UTC

**Comment by brianacox** [comment] 2021-03-05 11:05
> @brianacox zzh! as in the adapter. I've been using it for a while, but before i was using cc2531. What I was trying to say is that with the supervisor and hassos and latest z2m add-on everything works for me. I will close the issue for now. Any problems please raise a new issue.

Ok, understood.... I will try again today.
