### ISSUE TITLE
Bosch Room Thermostat II 230V (BTH-RM230Z): "Window Open" switch not showing in Home Assistant

### ISSUE THREAD

**Issue by csuermann** [zigbee2mqtt/hassio-zigbee2mqtt#567] opened 2024-02-08 07:26 UTC
### Description of the issue

In Zigbee2MQTT the thermostat exposes some switches
<img width="489" alt="image" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/10939809/2351f486-92e7-423b-b395-661105c31aba">

However, the "Window Open" switch does not show up in Home Assistant
<img width="668" alt="image" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/10939809/3adf2037-8f92-4415-b66b-7acc96a0e86e">

### Addon version

v1.35.3-1

### Platform

Core: 2024.2.0
Supervisor: 2024.01.1
Operating System: 11.5
Frontend: 20240207.0

**Comment by Koenkk** [comment] 2024-02-08 19:38
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/21208

**Closed by Koenkk** 2024-02-08 19:38 UTC
