### ISSUE TITLE
Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by Kepro** [zigbee2mqtt/hassio-zigbee2mqtt#516] opened 2023-08-04 14:11 UTC
### Description of the issue

I updated HA to latest version today :-)

This stops working in version 2024.2.0. Please address before upgrading.

```
Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

switch.server
switch.water_pump_socket
light.work_room_light_left
update.fish_socket
light.work_room_light_right
update.kids_room_socket
switch.kids_room_socket
light.living_room_lightbulb
update.work_room_light_left
light.work_room_lights
update.living_room_socket
```

### Addon version

1.32.2-1

### Platform

Home Assistant 2023.8.0
Supervisor 2023.07.1

**Comment by Koenkk** [comment] 2023-08-04 17:28
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Closed by Koenkk** 2023-08-04 17:28 UTC
