### ISSUE TITLE
Addon wont start because /dev/* is read only (Operation not permitted)

### ISSUE THREAD

**Issue by ciotlosm** [zigbee2mqtt/hassio-zigbee2mqtt#27] opened 2021-02-12 12:07 UTC
**Description of problem:**
There seem to be a problem with the combination of Supervisor & Zigbee2mqtt that causes problems with both Serial Port or Socat setup.

Creating this issue to correlate multiple issues created to try and pinpoint the best solution. 

According to #24 the new Supervisor 2021.02.06 introduced new code that might cause this: https://github.com/home-assistant/supervisor/commit/b8a976b3440c57bc6cd3f8617afcc632f57906ff

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
n/a

**Your entire configuration from the frontend (with sensitive fields redacted)**:
n/a

**Running platform (details from Suypervisor > System)**

Please make sure you post your details around Core & Supervisor & Operating System below
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

Related issues:
#26 #24 https://github.com/danielwelch/hassio-zigbee2mqtt/issues/535

**Comment by xtrem16081987** [comment] 2021-02-12 12:31
Ms de info Marius !

**Comment by bruvv** [comment] 2021-02-12 13:16
And also linking this where there are some sort of work arounds.
https://community.home-assistant.io/t/hass-io-on-synology-dsm-native-package/125559/1477

**Comment by fss** [comment] 2021-02-12 16:50
just tried on a fresh system (5.11), restored the backup and immediately failed :/ same issue, /dev/ttyXXX is readonly and in this weird 'audio' group.

/dev/serial/by-id/xxx -> shows correct file permissions, but since it's only a symlink to /dev/ttyXXX, add-on still won't start.

**Comment by xtrem16081987** [comment] 2021-02-12 19:37
so i followed this guys tutorial , and my stick now works and zigbee 2 mqtt also . 

back in business :))

https://github.com/Koenkk/zigbee2mqtt/issues/320

**Comment by fss** [comment] 2021-02-12 22:47
@ciotlosm after doing a clean install and NOT restoring from backup, add-on works as expected. there's sth wrong with the update procedure and not the add-on itself

**Comment by adeepn** [comment] 2021-02-13 15:45
After clean install I receive error:
"Error: Error while opening serialport 'Error: Error: Operation not permitted, cannot open /dev/ttyAML2'"

**Comment by RIP21** [comment] 2021-02-13 15:50
I confirm that installing the latest version of Supervisor on Synology and then reverting back to 2017.1.7 still keeps /dev/* to be read-only or I dunno what but that's my error.
```
Zigbee2MQTT:error 2021-02-13 16:41:43: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
```
Running the zigbee2mqtt outside of hass.io e.g. by manually installing docker image on my Synology confirmed to be working just fine. Pity that all the devices have to be re-paired and then renamed in Home Assistant but at least I can get my stuff working again.

**Comment by ciotlosm** [comment] 2021-02-15 08:27
I think the supervisor is doing something funky with permissions. I upgraded OS and I upgraded the supervisor (running on a RPI4) and I have none of these problems. Might be worth asking on an issue in https://github.com/home-assistant/supervisor/issues

**Comment by fss** [comment] 2021-02-15 08:42
@ciotlosm after installing latest OS from scratch and only restoring the zigbee2mqtt add-on configuration I got it up and running. file permissions still seem to be completely borked, but since it works I can't truly say what was the issue

**Comment by remcopoulus** [comment] 2021-02-17 10:24
> Running the zigbee2mqtt outside of hass.io e.g. by manually installing docker image on my Synology confirmed to be working just fine. Pity that all the devices have to be re-paired and then renamed in Home Assistant but at least I can get my stuff working again.

I an quite new to everything, can you maybe explain how this is done or where I can find a tutorial to follow

**Comment by RIP21** [comment] 2021-02-17 13:05
You need to start with MQTT Broker installation
https://www.youtube.com/watch?v=w2eLoQHzQS0&ab_channel=BeardedTinker
Then install zigbee2mqtt using this tutorial (highly recommend using their frontend, after installation check this [page](https://www.zigbee2mqtt.io/information/frontend.html))
https://www.youtube.com/watch?v=HbkXQErileU&ab_channel=BeardedTinker
After that, you need to go to the home assistant and add new integration with the MQTT name.
I think this part may be in one of the videos above.

**Comment by MaxParameter** [comment] 2021-03-25 09:33
I Have the same problem:

CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-03-25 14:01:43: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-25 14:01:43: Failed to start zigbee
Zigbee2MQTT:error 2021-03-25 14:01:43: Exiting...
Zigbee2MQTT:error 2021-03-25 14:01:43: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Driver.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:159:28)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:157:45)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-25T09_31_43_907Z-debug.log

**Comment by muuuh** [comment] 2021-04-11 17:24
Is there a fix for this?

To my understanding hassio internally launches the add-ons as docker containers. According to `docker inspect -f '{{ .Mounts }}' [container-id of zigbee2mqtt]` the device /dev/ttyACM0 doesn't seem to be mapped to the container.

Perhaps it would help to launch the zigbee2mqtt container with the docker flag '--privileged'. Perhaps this is means disable "Protection mode" at Home Assistant - https://developers.home-assistant.io/docs/add-ons/security/?

**Closed** 2021-08-12 13:03 UTC
