### ISSUE TITLE
Problem Aqara E1

### ISSUE THREAD

**Issue by ShammanIT** [zigbee2mqtt/hassio-zigbee2mqtt#540] opened 2023-12-02 16:12 UTC
### Description of the issue

After updating to version 1.34.0-1, a problem arose with the Aqara E1 switch (without neutral). Switching to logical switch mode stopped working.

### Addon version

1.34.0-1

### Platform

core-2023.11.3
supervisor-2023.11.6
doker 24.0.7

### Logs of the issue (if applicable)

Zigbee2MQTT:info  2023-12-02 21:02:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'operation_mode' to 'Коридор/Туалет' failed: 'Error: undefined is not a object, got string (\"decoupled\")'","meta":{"friendly_name":"Коридор/Туалет"},"type":"zigbee_publish_error"}'

**Comment by Koenkk** [comment] 2023-12-02 19:06
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19960

**Closed by Koenkk** 2023-12-02 19:06 UTC
