### ISSUE TITLE
TS011F_plug_3 Power sensor not updating correctly after updating to v1.30.4-1

### ISSUE THREAD

**Issue by mrdroopy** [zigbee2mqtt/hassio-zigbee2mqtt#486] opened 2023-05-03 10:28 UTC
### Description of the issue

After applying last update, the TS011F plugs keep reporting last power state giving false power results if plug has been switched off or if the power drawn has dropped to zero. As soon as the plug is activated AND there is some power drawn from the plug, it will start updating again.

### Addon version

v1.30.4-1

### Platform

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend-versie: 20230411.1 - latest

**Comment by Koenkk** [comment] 2023-05-03 17:46
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/16709

**Closed by Koenkk** 2023-05-03 17:46 UTC
