### ISSUE TITLE
Crash after update to 1.31.0-1

### ISSUE THREAD

**Issue by silvinojr** [zigbee2mqtt/hassio-zigbee2mqtt#493] opened 2023-06-01 23:49 UTC
### Description of the issue

Today my Zigbee2MQTT updated to 1.31.0-1. Now it cannot start anymore:

[20:24:18] INFO: Preparing to start...
[20:24:18] INFO: Socat not enabled
[20:24:19] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

Any ideas on how to fix this?
I have tried to restart everything e replace USB cabe without success. 
Thanks!

### Addon version

v1.31.0-1

### Platform

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

### Logs of the issue (if applicable)

[20:24:18] INFO: Preparing to start...
[20:24:18] INFO: Socat not enabled
[20:24:19] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

**Comment by Koenkk** [comment] 2023-06-02 07:25
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/17863#issuecomment-1573279515

**Closed by Koenkk** 2023-06-02 07:25 UTC
